/*
* This class is responsible for processing various banking transactions by interacting with the AccountDatabase.
* This is the user interface class
* @authors Pranav Gummaluri, Yasasvi Tallapaneni
*/

import java.util.Calendar;
import java.util.Scanner;

public class TransactionManager {
    private AccountDatabase accountDatabase;
    private Scanner scanner;

    //Main method to run the class
    public static void main(String [] args) {
        TransactionManager manager = new TransactionManager();
        manager.run();
    }

    //Constructor initializes the accountDatabase and prints a message indicating that the transaction manager is running.
    public TransactionManager() {
        this.accountDatabase = new AccountDatabase();
        System.out.println("Transaction Manager is running.");
        System.out.println();
    }

    //This method sets up a Scanner to read user input and run the interface
    public void run() {
        scanner = new Scanner(System.in);
        while (true) {
            String input = scanner.nextLine().trim();
            if (!input.isEmpty() && !processTransaction(input)) {
                System.out.println("Transaction Manager is terminated.");
                break;
            }

        }
        scanner.close();
    }

    /*
    * Method processes individual transactions based on the input string.
    * @param the input transaction string generated by the user
    * @return a boolean to see if it is a valid inout
    */ 
    public boolean processTransaction(String transaction) {
        if (transaction == null) {
            return true;
        }
        String[] preProcessedTokens = transaction.split("\\s+");
        String [] tokens = new String[7];
        int index = 0;
        for (String preProcessedToken : preProcessedTokens) {
            if (!preProcessedToken.isEmpty()) tokens[index++] = preProcessedToken;
        }

        String command = tokens[0];
        switch (command) {
            case "O":
                openAccount(tokens, index);
                break;
            case "C":
                closeAccount(tokens, index);
                break;
            case "D":
                deposit(tokens, index);
                break;
            case "W":
                withdraw(tokens, index);
                break;
            case "P":
                printSorted();
                break;
            case "PI":
                printFeesAndInterests();
                break;
            case "UB":
                updateBalances();
                break;
            case "Q":
                return false;
            default:
                System.out.println("Invalid command!");
        }
        return true;
    }

    /*
    * Method that opens the account based on the appropriate input
    * @param the string array of tokens from the user, and the index number
    */
    private void openAccount(String[] tokens, int index){
        if (index < 6) {
            System.out.println("Missing data for opening an account.");
            return;
        }
        String accountType = tokens[1].trim();
        String firstName = tokens[2];
        String lastName = tokens[3];
        String dobString = tokens[4];
        if (!isValidAmount(tokens[5])) {
            return;
        }
        double initialDeposit = Double.parseDouble(tokens[5]);
        Date dob = parseDate(dobString);
        if (dob == null) {
            return;
        }
        Profile profile = new Profile(firstName.substring(0,1).toUpperCase() + firstName.substring(1).toLowerCase(), lastName.substring(0,1).toUpperCase() + lastName.substring(1).toLowerCase(), dob);
        if (accountType.equals("CC") && !isValidCampusCode(tokens)) {
            return;
        }
        if (accountType.equals("CC") || accountType.equals("C")) {
            if (accountDatabase.hasCheckingOrCollegeChecking(profile, accountType)) {
                printError(firstName, lastName, dob, accountType);
                return;
            }
        }
        Account account = createNewAccount(accountType, profile, initialDeposit, tokens);
        if (account == null) {
            return;
        }
        if (accountDatabase.open(account)) {
            System.out.println(profile.toString() + "(" + accountType + ") opened.");
        } else {
            System.out.println(profile.toString() + "(" + accountType + ") is already in the database.");
        }
    }

    private boolean isValidAmount(String amountStr) {
        try {
            double amount = Double.parseDouble(amountStr);
            if (amount <= 0) {
                System.out.println("Initial deposit cannot be 0 or negative.");
                return false;
            }
        } catch (NumberFormatException nfe) {
            System.out.println("Not a valid amount.");
            return false;
        }
        return true;
    }

    /*
    * Method that opens the account based on the appropriate input
    * @param string representation of the user's date of birth 
    * @return a Date object that is given in the specified syntax
    */
    private Date parseDate(String dobString) {
        String[] dobTokens = dobString.split("/");
        int month = Integer.parseInt(dobTokens[0]);
        int day = Integer.parseInt(dobTokens[1]);
        int year = Integer.parseInt(dobTokens[2]);

        if (!isValidDOB(month, day, year)) {
            return null;
        }

        return new Date(month, day, year);
    }

    /*
    * Method that checks if the inputs given match the set commands
    * @param the string array of tokens inputted by the user
    * @return a boolean to indicate a valid command
    */
    private boolean isValidCampusCode(String[] tokens) {
        if (tokens.length < 7 || tokens[6] == null) {
            System.out.println("Invalid number of tokens");
            return false;
        }

        int campusCode;
        try {
            campusCode = Integer.parseInt(tokens[6]);
            if (campusCode < 0 || campusCode > 2) {
                System.out.println("Invalid campus code.");
                return false;
            }
        } catch (NumberFormatException e) {
            System.out.println("Invalid campus code.");
            return false;
        }

        return true;
    }


    /*
    * Prints out the specified error statement if the account already exists
    * @param the First, last names and the DOB of the user, and the account type
    */
    private void printError(String firstName, String lastName, Date dob, String accountType) {
        System.out.println(firstName + " " + lastName + " " + dob.toString() + "(" + accountType + ") is already in the database.");
    }

    //Checks if the DOB entered is a valid real date
    //@param the int representations of the month, day and year
    //@return a boolean to indicate a valid DOB
    private boolean isValidDOB(int month, int day, int year) {
        Calendar calendar = Calendar.getInstance();
        int currYear = calendar.get(Calendar.YEAR);
        int currMonth = calendar.get(Calendar.MONTH);
        int currDay = calendar.get(Calendar.DATE);

        if (year > currYear || (year == currYear && month - 1 >= currMonth) || (year == currYear && month - 1 == currMonth && day >= currDay)) {
            System.out.println("DOB invalid: " + month + "/" + day + "/" + year + " cannot be today or a future day.");
            return false;
        }
        Date dob = new Date(month, day, year);
        if (!dob.isValid()) {
            System.out.println("DOB invalid: " + month + "/" + day + "/" + year + " not a valid calendar date!");
            return false;
        }

        return true;
    }

    //Creates a new account based on the inputs of the user
    //@param, the account type, the user profule, the initial balance, and the array of input tokens
    //@return a new account object with the information inputted by the user
    private Account createNewAccount(String accountType, Profile profile, double initial, String [] tokens) {
        Date dob = profile.getDob();
        int age = getAge(dob);
        if (age < 16) {
            System.out.println("DOB invalid: " + dob.toString() + " under 16.");
            return null;
        }
        switch (accountType) {
            case "C":
                return new Checking(profile, initial);
            case "CC":
                if (age >= 24) {
                    System.out.println("DOB invalid: " + dob.toString() + " over 24.");
                    return null;
                }
                int campusCode = Integer.parseInt(tokens[6]);
                return new CollegeChecking(profile, initial, campusCode);
            case "S":
                boolean isLoyal = Integer.parseInt(tokens[6]) != 0;
                return new Savings(profile, initial, isLoyal);
            case "MM":
                if (initial < 2000) {
                    System.out.println("Minimum of $2000 to open a Money Market account.");
                    return null;
                }
                return new MoneyMarket(profile, initial);
            default:
                System.out.println("Invalid account type.");
                return null;
        }
    }

    //Creates a temporary Account object 
    //@param  account type, profile information, initial balance, and additional tokens
    //@return an Account object with the inputted information 
    private Account createTempAccount(String accountType, Profile profile, double initial, String [] tokens) {
        Date dob = profile.getDob();
        switch (accountType) {
            case "C":
                return new Checking(profile, initial);
            case "CC":
                return new CollegeChecking(profile, initial, 0);
            case "S":
                return new Savings(profile, initial, true);
            case "MM":
                if (initial < 2000) {
                    System.out.println("Minimum of $2000 to open a Money Market account.");
                    return null;
                }
                return new MoneyMarket(profile, initial);
            default:
                System.out.println("Invalid account type.");
                return null;
        }
    }

    //Calculates the age of the user based on the DOB
    //@param the Date object dob representing the DOB of the user
    //@return the age of the user based on the input
    public int getAge(Date dob) {
        Date currentDate = new Date();
        int age = currentDate.getYear() - dob.getYear();
        if (currentDate.getMonth() < dob.getMonth() || (currentDate.getMonth() == dob.getMonth() && currentDate.getDay() < dob.getDay())) {
            age--;
        }
        return age;
    }

    //This method handles the account closing transaction
    //@param array of tokens from input command and index for number of tokens
    private void closeAccount(String[] tokens, int index) {
        if (index < 5) {
            System.out.println("Missing data for closing an account.");
            return;
        }

        String accountType = tokens[1];
        accountType = accountType.trim();
        String firstName = tokens[2];
        String lastName = tokens[3];
        String dobString = tokens[4];
        Date dob = new Date(dobString);
        if (!isValidDOB(dob.getMonth(), dob.getDay(), dob.getYear())) {
            return;
        }
        Profile profile = new Profile(firstName, lastName, dob);
        Account accountToClose = createTempAccount(accountType, profile, 5000, tokens);
        if (accountToClose == null) {
            return;
        }
        if (accountDatabase.close(accountToClose)) {
            System.out.println(profile.toString() + "(" + accountType + ") has been closed.");
        } else {
            System.out.println(profile.toString() + "(" + accountType + ") is not in the database.");
        }

    }

    //This method handles the deposit transaction
    //@param array of tokens from input command and index for number of tokens
    private void deposit(String[] tokens, int index) {
        if (index < 6) {
            System.out.println("Missing data for depositing in an account.");
            return;
        }

        String accountType = tokens[1];
        accountType = accountType.trim();
        String firstName = tokens[2];
        String lastName = tokens[3];
        String dobString = tokens[4];
        double deposit = 0;
        try {
            deposit = Double.parseDouble(tokens[5]);
        } catch (NumberFormatException ne) {
            System.out.println("Not a valid amount.");
            return;
        }
        if (deposit <= 0) {
            System.out.println("Deposit - amount cannot be 0 or negative.");
            return;
        }
        Date dob = new Date(dobString);
        Profile profile = new Profile(firstName.substring(0,1).toUpperCase() + firstName.substring(1).toLowerCase(), lastName.substring(0,1).toUpperCase() + lastName.substring(1).toLowerCase(), dob);
        Account accountToDeposit = createTempAccount(accountType, profile, 5000, tokens);
        if (accountToDeposit == null) {
            return;
        }
        boolean canDeposit = accountDatabase.deposit(accountToDeposit, deposit);
        if (canDeposit) {
            System.out.println(firstName + " " + lastName + " " + dob.toString() + " (" + accountType + ") Deposit - balance updated.");
        } else {
            System.out.println(firstName + " " + lastName + " " + dob.toString() + " (" + accountType + ") is not in the database.");
        }
    }

    //This method handles the withdrawal transaction
    //@param array of tokens from input command and index for number of tokens
    private void withdraw(String[] tokens, int index) {
        if (index < 6) {
            for (int i = 0; i < index; i++) {
                System.out.println(tokens[i]);
            }
            System.out.println("Missing data for withdrawing from an account.");
            return;
        }
        String accountType = tokens[1].trim();
        String firstName = tokens[2];
        String lastName = tokens[3];
        String dobString = tokens[4];
        double withdrawAmount = 0;
        try {
            withdrawAmount = Double.parseDouble(tokens[5]);
        } catch (NumberFormatException ne) {
            System.out.println("Not a valid amount.");
            return;
        }
        if (withdrawAmount <= 0) {
            System.out.println("Withdraw - amount cannot be 0 or negative.");
            return;
        }
        Date dob = new Date(dobString);
        Profile profile = new Profile(firstName, lastName, dob);
        Account accountToWithdraw = createTempAccount(accountType, profile, 5000, tokens);
        if (accountToWithdraw == null) {
            return;
        }
        int canWithdraw = accountDatabase.withdraw(accountToWithdraw, withdrawAmount);
        if (canWithdraw == 2) {
            System.out.println(profile.toString() + "(" + accountType + ") Withdraw - balance updated.");
        } else if (canWithdraw == 0) {
            System.out.println(profile.toString() + "(" + accountType + ") is not in the database.");
        } else {
            System.out.println(profile.toString() + "(" + accountType + ") Withdraw - insufficient fund.");
        }
    }

    //Prints the sorted items
    private void printSorted() {
        accountDatabase.printSorted();
    }

    //Printes the fees and interests for the account
    private void printFeesAndInterests() {
        accountDatabase.printFeesAndInterests();
    }

    //updates the balance after calculating fees, interests and withdrawals
    private void updateBalances() {
        accountDatabase.calculateFeesAndInterests();
        accountDatabase.resetMoneyMarketWithdrawals();
        accountDatabase.printSorted();
    }

}
